# pytest: ollama, e2e
"""Basic example of using call_tools() to execute model-requested tool calls.

This example shows how to use the low-level call_tools() primitive to manually
execute tools generated by a model. While higher-level APIs like act() and
instruct() generate tool calls automatically, they do not execute them—you must
call call_tools() yourself to run the generated tools.

Use call_tools() when you need custom control over tool execution, such as
implementing a custom agentic loop or specializing context management.

Run:
  uv run python docs/examples/primitives/call_tools_basic.py
"""

from mellea import start_session
from mellea.backends import ModelOption, tool
from mellea.stdlib.functional import acall_tools, call_tools


@tool
def add(a: int, b: int) -> int:
    """Add two numbers."""
    return a + b


@tool
def multiply(a: int, b: int) -> int:
    """Multiply two numbers."""
    return a * b


def example_manual_tool_execution():
    """Show how to manually execute tool calls with call_tools()."""
    with start_session() as m:
        # Step 1: Generate with tool calls enabled
        print("Step 1: Generate with tool_calls=True")
        result = m.instruct(
            description="What is (2 + 3) * 4?",
            model_options={ModelOption.TOOLS: [add, multiply]},
            tool_calls=True,
        )
        print(f"  Model output: {result.value[:100]}...")

        # Step 2: Execute the tools using call_tools()
        print("\nStep 2: Execute tools with call_tools()")
        tool_messages = call_tools(result, m.backend)
        print(f"  Tool calls executed: {len(tool_messages)}")

        # Step 3: Show the results
        print("\nStep 3: Tool results")
        for i, tool_msg in enumerate(tool_messages):
            print(f"  Tool {i + 1}: {tool_msg.name}")
            print(f"    Arguments: {tool_msg.arguments}")
            print(f"    Output: {tool_msg._tool_output}")
            print(f"    Content: {tool_msg.content}")


def example_context_management():
    """Show how to manage context when using call_tools()."""
    import asyncio

    from mellea.stdlib.components import Message
    from mellea.stdlib.context import SimpleContext
    from mellea.stdlib.functional import aact

    async def run():
        with start_session() as m:
            ctx = SimpleContext()

            # Add an initial message
            user_msg = Message("user", "Add 10 and 20")
            ctx = ctx.add(user_msg)
            print("Step 1: Added user message to context")

            # Generate with tools using functional API
            result, ctx = await aact(
                user_msg,
                ctx,
                m.backend,
                model_options={ModelOption.TOOLS: [add, multiply]},
                tool_calls=True,
                await_result=True,
            )
            print("Step 2: Generated response with tool calls")

            # Execute tools and add results manually
            tool_messages = await acall_tools(result, m.backend)
            print(f"Step 3: Executed {len(tool_messages)} tool(s)")

            for tool_msg in tool_messages:
                ctx = ctx.add(tool_msg)
            print("Step 4: Added tool results to context")

    asyncio.run(run())


if __name__ == "__main__":
    print("=" * 60)
    print("Example 1: Manual tool execution with call_tools()")
    print("=" * 60)
    example_manual_tool_execution()

    print("\n" + "=" * 60)
    print("Example 2: Context management with call_tools()")
    print("=" * 60)
    example_context_management()
